### ISSUE TITLE
modify IMediaDataSouce.java create new jni file error 

### ISSUE THREAD

**Issue by 0ct0cat** [Bilibili/jni4android#2]
I add a new function in IMediaDataSouce.java want to create a IMediaDataSource.c/h file.
make test have problem understand.

Unknown token at line 9: '"'
ERROR: at line 9
	syntax error
make: *** [jni/j4a/class/tv/danmaku/ijk/media/player/misc/IMediaDataSource.c] 错误 1

**Comment by bbcallen** [comment]
Need more information.

**Comment by 0ct0cat** [comment]
modify the IMediaDataSource.java in test/i_java/tv/danmaku/ijk/media/player/misc folder  to

@SimpleCClassName
public interface IMediaDataSource {
    void open(String uri, String headers);
    int  readAt(long position, byte[] buffer, int size);
    void close();
    long getSize();
    String getUri();
}
then run the make test 

the jni c file can't create normal.

**Comment by bbcallen** [comment]
What is at line 9?

**Comment by 0ct0cat** [comment]
sorry i make a mistake. 

the new IMediaDataSource.java is 
@SimpleCClassName
public interface IMediaDataSource {
   void open(String uri, String headers) throws IOException;
    int  readAt(long position, byte[] buffer, int size);
    void close();
    long getSize(); 
    String getUri();
}
there is one more  IOException.
line 9 just the last line. no special.
the j4a can't  support function throw exception?

but there is another problem. delete the IOException.
i run the j4a command in shell.just like describe below.can create the c/h file success.
./j4a -c test/i_java/tv/danmaku/ijk/media/player/misc/IMediaDataSource.java -o test/ref_c/tv/danmaku/ijk/media/player/misc/IMediaDataSource.c

but run make test will be failed.like 
make: *** [jni/j4a/class/tv/danmaku/ijk/media/player/misc/IMediaDataSource.c] 错误 1
there is  a issue in makefile ?

**Comment by bbcallen** [comment]
There would be no difference in generated c source code, with or without 'throws IOException',
thus it doesn't make any sense to support IOException

Try make --debug

**Comment by 0ct0cat** [comment]
ok,i know the reason of this error.
when i modify the .java file,make .c file success.
but 
diff test/ref_c/$*.c 			$@ 
report error.

thx.
