### ISSUE TITLE
C wrapper files was wrong with int array

### ISSUE THREAD

**Issue by DarkKnightSG** [Bilibili/jni4android#5]
Wrong C wrapper generated result for all types of primitive type array such as: int[], boolean[], float[]
Example: 
public int testIntArray(int[] iArr);
public float testFloatArray(float[] fArr);
public double testDoubleArray(int[] iArr);
Result: 
**_jintArray_** J4AC_android_os_Test__testIntArray(JNIEnv *env, jobject thiz, jintArray iArr);
**_jintArray_** J4AC_android_os_Test__testIntArray__catchAll(JNIEnv *env, jobject thiz, jintArray iArr);
**_jintArray_** J4AC_android_os_Test__testIntArray__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jintArray iArr);
**_jfloatArray_** J4AC_android_os_Test__testFloatArray(JNIEnv *env, jobject thiz, jfloatArray fArr);
**_jfloatArray_** J4AC_android_os_Test__testFloatArray__catchAll(JNIEnv *env, jobject thiz, jfloatArray fArr);
**_jfloatArray_** J4AC_android_os_Test__testFloatArray__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jfloatArray fArr);
jdouble J4AC_android_os_Test__testDoubleArray(JNIEnv *env, jobject thiz, jintArray iArr);
jdouble J4AC_android_os_Test__testDoubleArray__catchAll(JNIEnv *env, jobject thiz, jintArray iArr);
Expected:
**jint** J4AC_android_os_Test__testIntArray(JNIEnv *env, jobject thiz, jintArray iArr);
**jint** J4AC_android_os_Test__testIntArray__catchAll(JNIEnv *env, jobject thiz, jintArray iArr);
**jint** J4AC_android_os_Test__testIntArray__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jintArray iArr);
**jfloat** J4AC_android_os_Test__testFloatArray(JNIEnv *env, jobject thiz, jfloatArray fArr);
**jfloat** J4AC_android_os_Test__testFloatArray__catchAll(JNIEnv *env, jobject thiz, jfloatArray fArr);
**jfloat** J4AC_android_os_Test__testFloatArray__asGlobalRef__catchAll(JNIEnv *env, jobject thiz, jfloatArray fArr);
jdouble J4AC_android_os_Test__testDoubleArray(JNIEnv *env, jobject thiz, jintArray iArr);
jdouble J4AC_android_os_Test__testDoubleArray__catchAll(JNIEnv *env, jobject thiz, jintArray iArr);

**Comment by bbcallen** [comment]
Fixed in v0.0.3.
Thanks.
